name: proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dise침o y Utilidades B치sicas
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  path: ^1.9.0
  intl: ^0.20.2
  fl_chart: ^0.65.0

  # HTTP y Base de Datos
  http: ^1.4.0 
  sqflite: ^2.4.2

  # Supabase (Backend)
  supabase_flutter: ^2.8.4
  supabase: ^2.6.3
  gotrue: ^2.11.1
  postgrest: ^2.4.1
  realtime_client: ^2.4.2
  storage_client: ^2.3.1
  flutter_dotenv: ^5.1.0

  # WebView
  webview_flutter: ^4.8.0

  # Autenticaci칩n
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.3.0

  # Geolocalizaci칩n y Mapas
  geolocator: ^14.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env